### ISSUE TITLE
Feature Request: Has/Lacks file

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/ShellAndTest#6]
A lot of the errors we traditionally have with Dockerized game servers happens when either an unexpected file sneaks its way into the image, or when a expected file doesn't make it into an image. This happens more often than you'd think, because the way core game servers are downloaded using utilities likes SteamCMD.

I'd be great, if there were mechanisms where checks for the existence of, or a lack of file(s) could themselves be a check.

Maybe something like:

```yaml
target:
    ......
    files_exist:
        - /path/to/file1
        - /path/to/file2
        - /path/to/file3
    files_absent:
        - /path/to/file4
        - /path/to/file5
        - /path/to/file6
```

If issue #5 is implemented, I would make this feature only work with docker-images target type for now.

Using the Docker libraries, it should be able to check for the existence of files w/o spinning up the image. This could be useful if the only tests we want to preform are these file checks (for example, in our content server proxy docker image).
