### ISSUE TITLE
Feature Request: Grouping

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/ShellAndTest#8]
Sometimes, a series/combination of `should_have` and `should_lack` tests belong together, if they are all testing the same sub-portion of the system under test (e.g., testing source mod specifically in a csgo server). It'd be nice to have a mechanism to group these together in the YAML, similar to feature request (Issue #7), while having them apply to a single `execute` element.

```yaml
target: 
	execute: docker run --rm -it ubuntu /bin/ash    # <------ THIS IS THE COMMAND THE KICKS OFF THE "ROOT" TEST
		should_lack:     # <---- NOTICE THIS IS NOW NESTED UNDERNEATH EXECUTE
			 - string1
			 - string 2
			 - string 3
		should_have:
			- string 4
			- string 5
			- string 6
		
		group:	# <----- THIS EXECUTE IS NESTED UNDEARNEATH THE ROOT ONE, EXECUTING A FIRST "SUB TEST"
                        name: "test aspect y"
			should_lack:
				- string 7
				- string 8
				- string 9
			should_have:
				- string 10
				- string 11
				- string 12
						
		execute:	# <----- THIS EXECUTE IS NESTED UNDEARNEATH THE ROOT ONE, EXECUTING A SECOND "SUB TEST"
                        name: "test aspect y"
			should_lack:
				- string 13
				- string 14
				- string 15
			should_have:
				- string 16
				- string 17
				- string 18
```
